name: Keploy Test
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Install Keploy
        run: |
          curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz --overwrite -C /tmp
          sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploy

      - name: Keploy Tests
        run: keploy test -app src/app.js -dir ./keploy

      - name: Upload Keploy Reports
        uses: actions/upload-artifact@v4
        with:
          name: keploy-reports
          path: ./keploy/reports/
